# Platform-agnostic YAML - appId and device are replaced at runtime
# Default values (will be replaced by runMaestroTest based on platform):
appId: com.mycodepushapp
device: android

---
- launchApp
- assertVisible: "Update available"
- assertVisible: "A new version of the app is available. Would you like to update?"
- tapOn: "Install"
- waitForAnimationToEnd:
    timeout: 15000 
- assertNotVisible:
    text: "DOTA Updated bundle loaded successfully🚀"

- launchApp
- assertVisible: "💡 Open App.tsx to get started"